name: single_web_page
description: "Single Web Page implementation for Flutter Web"

publish_to:

version: 1.0.5
homepage: https://github.com/commandiron/single_web_page

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true