name: single_web_page
description: "Create Single Web Page Layout with adaptive scrollable implementations."
homepage: https://github.com/commandiron/single_web_page
repository: https://github.com/commandiron/single_web_page

version: 1.1.4

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true